language: node_js
branches:
  only:
  - master
node_js:
- '7'
rust:
- stable
python:
- '3.5'
before_install:
- npm install
install:
- pip install ghp-import
script:
- make github
env:
  global:
  - secure: mdqrJXQrVqH8uJhnaeYnydoZGUERsFd0nrBe/XSC3M6sMhKz/SF0722AS+VRwhuMARwJA1F6hvIJJCLIZrsiWDaKYzQxRza0YdKt/3fT52uLbBXyFHaqsj0cOX1h7hWHstlh4AWc3uYFRvv097y8iJJnwSjTUo1DVs9Orw2jhO0NVXtKgVOAESrGNyX0p2J6+YGylYaIMCqemOoME1fy9bpixHIDJcKHAZlni/yV4sDt2fBzSEVQlCpikfA+1KDkNK/6I/rr+dqXUOKOqiGXQ1WrV5oaxzFqc8Ie19vtnE1IL755Xb3nIHDj6fFCAJInrno071IcKWUouGgsWmDgcpUSahFytDYPZ8QtEFlW3Ervki1Ow2QDlJJAKjY0wVb01ktwULNI/Fo7Mmb6czEaC+X6D9D38JUJevn+wdT/3bx+Zt/YwAJCnhbY8elftft9wOOWl3jLqEhblOyFP4WRlpnP1br5R5jDb9WrZhgOCJfVwETUg+7uC3V5qyQh2yZ0io5ZopMVkE8usGFbO+aeMRKAT2UbzxqHXLy/10GYO2nYmfDfsFCi41QfmCsZAYtmPzpwtiGli9e9sWWoBDVQF65xEsFWETWQjokbJ9UNDf2iZxlFa1BaQb2v/BGmEPPgApXmaB7lUl5aeSMg2VeCLJWQ5orT4Uiu6ok0hvY7Ph0=
  - secure: Hyvf+gagJUnl257bshNt3fHNFm6zu/JI4HwINC5GHT3E/g+kkclapDzbdHunjPv/qpNnxWihujXFxlHNloTxcBT5HGmaAFhiR35xlcirouA3gfdqcnluK7XTu8yJU7rG7OplScwsMH8tW6It0TOql4k5OfiYzkNmFiaK1+Ccajm5scoAZqT7mzBWK5H799ji8tIQ1KpaJk6xTGrwDbD1pl5Dn8QyMjDwJRztgE8Q2PxPTTyOlwwAKeDyiKpWsNOAzeq198pgf0EP/qkhOYvA5En5CR1ZiWeiowmb8U/w+Vj/BO+JZJHXspnU+/uUEatsje/zLbMgTwKBGA5AYHbfmqr68aNy60HAHc8obrF97lBWwMM6+ab9g38uaSn35IS38bmtBFzaXJuNufPvla0NAmwL0FYJrR35oOrdl8CEZjXv29J2wUhXs6ZZRgTPEC8+bya0heGOzOu626AhiKZEj9GcjyL/+mK+ZpTJBqynoc+d5GPBlfqxTrSbPoTiwzvBtIXCTzIZ/ENHgzZx3phzc4hLIx/wAYv4Oknrif/XPPZXEDvBX++i0tuhR04CbZiafwaXd9fQ2HGIG/scXJCtyHjpctzFZ8dshvTWeneLNh/IWwV5RqYo7OEMAjYj60EmdGav5Ga7/+ep5HALBndLa0vLg/hw/a+pzEuF78Uph1U=
