language: rust
branches:
  only:
  - master
node_js:
- '7'
rust:
- stable
python:
- '3.5'
before_install:
- npm install
install:
- pip install --user ghp-import
script:
- make github
env:
  global:
  - secure: mdqrJXQrVqH8uJhnaeYnydoZGUERsFd0nrBe/XSC3M6sMhKz/SF0722AS+VRwhuMARwJA1F6hvIJJCLIZrsiWDaKYzQxRza0YdKt/3fT52uLbBXyFHaqsj0cOX1h7hWHstlh4AWc3uYFRvv097y8iJJnwSjTUo1DVs9Orw2jhO0NVXtKgVOAESrGNyX0p2J6+YGylYaIMCqemOoME1fy9bpixHIDJcKHAZlni/yV4sDt2fBzSEVQlCpikfA+1KDkNK/6I/rr+dqXUOKOqiGXQ1WrV5oaxzFqc8Ie19vtnE1IL755Xb3nIHDj6fFCAJInrno071IcKWUouGgsWmDgcpUSahFytDYPZ8QtEFlW3Ervki1Ow2QDlJJAKjY0wVb01ktwULNI/Fo7Mmb6czEaC+X6D9D38JUJevn+wdT/3bx+Zt/YwAJCnhbY8elftft9wOOWl3jLqEhblOyFP4WRlpnP1br5R5jDb9WrZhgOCJfVwETUg+7uC3V5qyQh2yZ0io5ZopMVkE8usGFbO+aeMRKAT2UbzxqHXLy/10GYO2nYmfDfsFCi41QfmCsZAYtmPzpwtiGli9e9sWWoBDVQF65xEsFWETWQjokbJ9UNDf2iZxlFa1BaQb2v/BGmEPPgApXmaB7lUl5aeSMg2VeCLJWQ5orT4Uiu6ok0hvY7Ph0=
  - secure: wMK0ggGgfhfsNtQT7R9ryLRsDZ8i3nKUXR2aMdVeXnMXzAci9BXkhu2Cs86RjkSR8vXvC0jw62cR+DsiTXat8r9RcjUy1GCKVRMX8kSiTGATxVvxWOzVjqqIcaBVWnXxEXbVMQI2oIHnJwdxcq1luVdpqhdKxwgTT+TpDlhr+43auSxpwd4vYIA+ad2lcOF9akDKBIaM+jfCqDymE2pyB2VifdCQcvUI8hitI2B2ESNxFMkebzZFmyGUCqp9Y5OqsCPFMEnhxmiJ0vrgfFBSv2y7unANt07gwERldqApK1PURDyEEDzTBT/vLUzOAYNjLtD74LC887ZXxqSHWrlPBKoAk37iK6mkuOGQVNDHSSc4cYKmEf9J3SzjoNXE/3xkuSuv8v1WF0CjtAU9hBpjXmjYidwJ7ELiNoz2mGGVIkkmtVC40SSADs0HH25WsDBEgh9jZrntCw3pF48sytEKlSa3mZRahmgPVTza1mv8MtIkgV5+r2mZ+wYdNefWuPEFN0lQ4dJhtDm+OXxmn8StD7D/feHZ5YNgJtvoEpPrQeOJ/s0TbgOt/HZaAoHTiKu2SvFQqLHo9l2+vERIwghCNT+boRuFNPEQanycr2MhRlW88d+cLaPDDZccoL9B54gzNlyeW/AkGwNPGWIcR18feVfgtHmva+3u4+duUApXZR8=
