language: rust
branches:
  only:
  - master
node_js:
- '7'
rust:
- stable
python:
- '3.5'
before_install:
- npm install
install:
- pip install --user ghp-import
script:
- make github
env:
  global:
  - secure: mdqrJXQrVqH8uJhnaeYnydoZGUERsFd0nrBe/XSC3M6sMhKz/SF0722AS+VRwhuMARwJA1F6hvIJJCLIZrsiWDaKYzQxRza0YdKt/3fT52uLbBXyFHaqsj0cOX1h7hWHstlh4AWc3uYFRvv097y8iJJnwSjTUo1DVs9Orw2jhO0NVXtKgVOAESrGNyX0p2J6+YGylYaIMCqemOoME1fy9bpixHIDJcKHAZlni/yV4sDt2fBzSEVQlCpikfA+1KDkNK/6I/rr+dqXUOKOqiGXQ1WrV5oaxzFqc8Ie19vtnE1IL755Xb3nIHDj6fFCAJInrno071IcKWUouGgsWmDgcpUSahFytDYPZ8QtEFlW3Ervki1Ow2QDlJJAKjY0wVb01ktwULNI/Fo7Mmb6czEaC+X6D9D38JUJevn+wdT/3bx+Zt/YwAJCnhbY8elftft9wOOWl3jLqEhblOyFP4WRlpnP1br5R5jDb9WrZhgOCJfVwETUg+7uC3V5qyQh2yZ0io5ZopMVkE8usGFbO+aeMRKAT2UbzxqHXLy/10GYO2nYmfDfsFCi41QfmCsZAYtmPzpwtiGli9e9sWWoBDVQF65xEsFWETWQjokbJ9UNDf2iZxlFa1BaQb2v/BGmEPPgApXmaB7lUl5aeSMg2VeCLJWQ5orT4Uiu6ok0hvY7Ph0=
  - secure: kgTgJM9hL5klwZVm51SIBiOY3i+ADLH5ZieQav3Fa29ftlO1eft6/TefkidR0lfBTgl5ci9wHrFb9FJIn6reEnaniu/UYk1ehU/l5ZvR4yiSZnPoDU2TWq6AREK8DdrSk63vcsc4FJ1lfnucJWctWLclsnylQqVxa1ktVI1miMhZboCI6XubDB6YBLJsarx1NYzTFeIJ1fk5xYVhN3gyGHQ6WG7rJEJ5SmMxzojwvIJ4KeomWPZ5NcUdtl5t54YisSD9S6dD2Avue0Gz6Nft35sSxQXrS2i6+Y2ieAqGikC/Vg6j2yZY1q30KHtgKjd+HT1c6O41CwyEY1yXfydohZdr5sx1rLPT821wjzZTtZoiO/1zYMDUdREKM0cckDapMvz4iUoRIJ+QEWIoROL/jPS5TcgahhHI1UKIuTpWj0rAYpMsjXbMXJApkwhFj+2wXVD4pRUZaeAI8dCh47ohuyxBp7Kd0oXQkQVgMxfuhPiyGFUuOBpS3G8+2kS8EXe6Er+/6mmm27Yt5mkNDQ5duFCpJ/t4xn+DJFQ89CJ7mkZcyycV9n2hovp+GfzRhfVvmqd1AOaMm/uSoBfz/h6c2gSZDe7WG31U1h7NW5AmF/Ze6zwM7WR7OJINrGG/9EjnxjMsafW+XlUxbZUoGof113E4uaf07OSvxd6jbwfdK24=
